import Foundation

/// `UserDefaults.standard` のキーの一元管理。生文字列を直接あちこちに書くと、
/// タイポで死んだキー(書き込み側と読み込み側でスペルが食い違い、値が永久に
/// 読めなくなる)に気づけないため、キー文字列はここでだけ定義する。
enum PrefsKey {
    static let hideMenuBarGlobal = "_HIHideMenuBar"
    static let advancedSharingEnabled = "advancedSharingEnabled"
    static let appLanguage = "appLanguage"
    static let audioEnabled = "audioEnabled"
    static let audioVolume = "audioVolume"
    static let autoFrameRateEnabled = "autoFrameRateEnabled"
    static let autoSwitchIntervalMinutes = "autoSwitchIntervalMinutes"
    static let autoUpdateEnabled = "autoUpdateEnabled"
    static let batteryAwareQualityEnabled = "batteryAwareQualityEnabled"
    static let clickThrough = "clickThrough"
    static let currentWebWallpaperID = "currentWebWallpaperID"
    static let decodeMode = "decodeMode"
    static let dedicatedPlaybackContinuityEnabled = "dedicatedPlaybackContinuityEnabled"
    static let desktopLevelOffset = "desktopLevelOffset"
    static let desktopReadabilityDimOpacity = "desktopReadabilityDimOpacity"
    static let displayMode = "displayMode"
    static let fitMode = "fitMode"
    static let focusFilterIntegrationEnabled = "focusFilterIntegrationEnabled"
    static let focusModeAssignmentsData = "focusModeAssignmentsData"
    static let frameRateLimit = "frameRateLimit"
    static let launchAtLogin = "launchAtLogin"
    static let libraryVideoPaths = "libraryVideoPaths"
    static let lightweightMode = "lightweightMode"
    static let lockScreenSyncEnabled = "lockScreenSyncEnabled"
    static let menuBarOpaqueEnabled = "menuBarOpaqueEnabled"
    static let menuBarSpaceNumberEnabled = "menuBarSpaceNumberEnabled"
    static let playlistPlaybackEnabled = "playlistPlaybackEnabled"
    static let playlistsData = "playlistsData"
    static let qualityPreset = "qualityPreset"
    static let registeredVideoDisplayNames = "registeredVideoDisplayNames"
    static let registeredVideoPaths = "registeredVideoPaths"
    static let respectReduceMotionEnabled = "respectReduceMotionEnabled"
    static let scheduleRulesData = "scheduleRulesData"
    static let screenPlaylistByScreenID = "screenPlaylistByScreenID"
    static let selectedPlaylistID = "selectedPlaylistID"
    static let shufflePlaybackEnabled = "shufflePlaybackEnabled"
    static let spaceWallpaperFeatureEnabled = "spaceWallpaperFeatureEnabled"
    static let suspendDisabledDisplayIDs = "suspendDisabledDisplayIDs"
    static let suspendExclusionBundleIDs = "suspendExclusionBundleIDs"
    static let suspendHighSensitivityEnabled = "suspendHighSensitivityEnabled"
    static let suspendWhenOtherAppFrontmost = "suspendWhenOtherAppFrontmost"
    static let suspendWhenOtherAppFullScreen = "suspendWhenOtherAppFullScreen"
    static let useFullScreenAuxiliary = "useFullScreenAuxiliary"
    static let videoBySpaceUUID = "videoBySpaceUUID"
    static let videoLoopEnabled = "videoLoopEnabled"
    static let videoOverrideByScreenID = "videoOverrideByScreenID"
    static let videoPath = "videoPath"
    static let wallpaperKind = "wallpaperKind"
    static let webWallpaperFeatureEnabled = "webWallpaperFeatureEnabled"
    static let webWallpaperSourcesData = "webWallpaperSourcesData"
    static let workProfile = "workProfile"
}
